theme = "carbonfox"

[editor]
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)

[keys.insert]
"A-k" = "normal_mode"     # Maps Alt-X to enter normal mode
